### ISSUE TITLE
Plugin causes sourcemap error

### ISSUE THREAD

**Issue by steveblue** [cebor/rollup-plugin-angular#1]
When sourceMap is equal to true, the plugin generates a lot of warnings in console, however appears to still work. Thanks for the example, it got me up and running with Rollup! My project's build was failing due to 404 from missing html and css because this crucial piece that was missing. 

```
export default {
  entry: 'src/main.ts',
  format: 'iife',
  dest: 'dist/bundle.es2015.js',
  sourceMap: true,
  plugins: [
    angular(),
    typescript(),
    alias({ rxjs: __dirname + '/node_modules/rxjs-es' }),
    resolve({ jsnext: true,
              main: true,
              browser: true }),
    replace({
      ENV: JSON.stringify(process.env.NODE_ENV || 'dev'),
    })
  ],
```

Here is the error :

Sourcemap is likely to be incorrect: a plugin ('angular') was used to transform files, but didn't generate a sourcemap for the transformation. Consult https://github.com/rollup/rollup/wiki/Troubleshooting and the plugin documentation for more information

**Comment by steveblue** [comment]
BTW @cebor This plugin is a must have for Angular 2 developers! TY for the contribution to the rollup community!

**Comment by cebor** [comment]
Just released a new version, should land in a few minutes on npm.

Can you test if the issues are solved?

**Comment by steveblue** [comment]
Fixed!
